on:
  push:
    branches:
      - master

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.clouduko.co.za
          username: sdumodesigns@clouduko.co.za
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
